### ISSUE TITLE
Arr helpers

### ISSUE THREAD

**Issue by Stunt** [tightenco/collect#15]
Does it make sense to add `Arr` helpers as well ? sometimes it's more convenient to use one of them and `Arr` class already available.

**Comment by mattstauffer** [comment]
Hey @Stunt, thanks for the idea! It's tempting to bring a lot of the other helpers in, but the whole point of this class is to be narrow. If you find yourself wanting to bring in other tools from the Illuminate Support library, there's nothing stopping you from just bringing in the Illuminate Support library in a project--it's not that heavy as-is.

Thanks!
