### ISSUE TITLE
Reduce does not work with chunk

### ISSUE THREAD

**Issue by janbodnar** [tightenco/collect#155]
I have an example where I use reduce with chunk. In the second call, 
the computation is `1*2 + 3*4 + 5*6`, which should give 44. It gives 2. 

I have worked with Collect.js, which is a port of Laravel's collections, where 
it works OK.

```
<?php

require 'vendor/autoload.php';

$nums = [1, 2, 3, 4, 5, 6];
$data = collect($nums);

$val = $data->reduce(function($c, $e) { return $e += $c; });
dump($val);

$val2 = $data->chunk(2)->reduce(function($c, $e) { 
    // echo $e->get(0) . "\n";
    // echo $e->get(1) . "\n";
    return $c + $e->get(0) * $e->get(1);
}, 0);

dump($val2);
```

**Comment by mattstauffer** [comment]
This library is just a reproduction of Laravel’s collections. If you try your example in Laravel does it work the way you want? 

If it works in Laravel but not this package, that’s a problem. 

If it works the same way in Laravel and this package, then you should make the issue in Laravel. 

Thanks!

**Comment by janbodnar** [comment]
It's the same in Laravel. 

I have created an issue there 
https://github.com/laravel/framework/issues/27844
