### ISSUE TITLE
[Bug ?] data_get helper cannot access properties of private object

### ISSUE THREAD

**Issue by Juyn** [tightenco/collect#164]
Hi,

I'm using Collect on a Symfony project, and, I have an issue while trying to 'pluck' or 'sum' some elements from my objects.

The specifity is that my object are using only private/protected objects (dunno why really ...), and the method 'data_get' cannot access this properties.

For now, I did managed to find a workarround, using Symfony\Component\PropertyAccess\PropertyAccess, but it's only for Symfony ...

**Comment by mattstauffer** [comment]
@juyn Hey! Thanks for the issue. Collect perfectly reproduces the code and functionality of Laravel's collection helper, so we can't change anything in here that isn't changed in the Laravel core. So any issues about changed functionality would have to go there: https://github.com/laravel/framework

That said, I think it's unlikely that `data_get` is modified to reach into private properties, but rather that it's expected that anything that'll be pulled in that way will have to be made public. I think `data_get` is likely more intended for use with `stdClass` or very dumb data transfer objects.

**Comment by Juyn** [comment]
Thanks for the reply.
Indeed, I didn't really thought that you would have implemented this feature, certainly not in that repo. But hey, I did have to try !

I did open an issue on Laravel's repo, without conviction tho.

However, it's a shame since it prevent me from using basic collection methods like pluck or sum.
I guess I'll just fork this repo, not such a big deal.
