### ISSUE TITLE
when i "composer  jaeger/querylist",but there are two errors shows?

### ISSUE THREAD

**Issue by eaglepie** [tightenco/collect#166]
i just want to use querylist, and so installed this  auto download,the messages are:

Warning: Class 'Tightenco\Collect\Support\Arr' not found in D:\Web\xxx\simplewind\vendor\tightenco\collect\src\Collect\Support\alias.php on line 16

Parse error: syntax error, unexpected '=' in D:\Web\xxx\simplewind\vendor\tightenco\collect\src\Collect\Support\Arr.php on line 384

how to fix them? anybody knows?

**Comment by SeanJA** [comment]
That seems like it might be a php version problem, what version of php do you have? The code on that line uses the list shorthand, which only became a thing in php 7.1 (I think?):

https://developer.hyvor.com/php-list

**Comment by eaglepie** [comment]
maybe,thank you .my PHP version is 7.0.12 nts or php 7.2.18, In laragon ,i switched the php version,But the same prompt is displayed.

**Comment by mattstauffer** [comment]
@eaglepie which version of Collect is this?

**Comment by eaglepie** [comment]
@mattstauffer the newest version.

**Comment by mattstauffer** [comment]
OK, that line is using array destructuring, which was introduced in PHP 7.1:

https://github.com/tightenco/collect/blob/5316c833a8c380d736b6e33a33a8781a50be3614/src/Collect/Support/Arr.php#L384

So the latest version of Collect works on 7.2 but not on 7.0, if I'm reading that correctly.

**Comment by SeanJA** [comment]
That's weird, because the composer file says 7.1.3:

https://github.com/tightenco/collect/blob/laravel-5.8-ongoing/composer.json#L13

**Comment by mattstauffer** [comment]
I wonder whether it was installed when the OP was using 7.2 but is now running on 7.0? Or differenr versions for web vs CLI, or local machine vs vagrant/vm?

**Comment by jamisonvalenta** [comment]
Closing this issue, as [php 7.1 is no longer maintained](https://www.php.net/supported-versions.php).
