### ISSUE TITLE
Symfony var-dumper requirement

### ISSUE THREAD

**Issue by MatusBoa** [tightenco/collect#168]
Hey,

I am getting this error when I try to run `composer update`:
```
Problem 1                                                                           
      - tightenco/collect v5.8.23 requires symfony/var-dumper >=3.4 <5 -> no matchin  
  g package found.  
```
I think it should be `^3.4.0` or `3.4.*` instead of `>=3.4 <5` or I am missing something?

Thanks.

**Comment by kotass** [comment]
Tried to require `>=3.4 <3.5` and it works :thinking:

**Comment by anthonyterrell** [comment]
Hey @kotass, 

I'm having difficulties replicating this issue, can you tell me the steps you took to reproduce this or what version of Collect this occurred on?

**Comment by kotass** [comment]
Hey @anthonyterrell,

I just did `composer update`, to update all my packages and error i shared earlier just occurs out of nowhere.. I forked your package, updated dependency to `>=3.4 <3.5` instead of `>=3.4 <5`, and it just works.
