### ISSUE TITLE
Support for Laravel 6.0 LazyCollection

### ISSUE THREAD

**Issue by stevebauman** [tightenco/collect#180]
With Laravel 6.0 being released with [LazyCollection](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Support/LazyCollection.php)'s, is this going to be implemented soon?

I can try writing a PR if necessary!

Thanks!

**Comment by mattstauffer** [comment]
We'd definitely love to! A PR would be nice--the tough part there is we would also have to modify that `upgrade.sh` script to get its files over, and its tests. I'll assign this to you and if you can't grok it please let us know!

**Comment by stevebauman** [comment]
Ok sounds good @mattstauffer! I’ll give it a go this weekend :smile:

**Comment by mattstauffer** [comment]
@stevebauman So... @anthonyterrell informed me we already have it! :)

**Comment by stevebauman** [comment]
Ah perfect, thanks @mattstauffer! :)
