### ISSUE TITLE
PHP Warning:  Class 'Tightenco\\Collect\\Support\\LazyCollection' not found

### ISSUE THREAD

**Issue by Ejike94** [tightenco/collect#181]
Hello, 

Today after a Composer update I started getting the following errors:
 PHP Warning:  Class 'Tightenco\\Collect\\Support\\LazyCollection' not found in /home/ubuntu/...../tightenco/collect/src/Collect/Support/alias.php on line 19

PHP Parse error:  syntax error, unexpected '=' in 
/home/ubuntu/...../tightenco/collect/src/Collect/Support/LazyCollection.php on line 563

I was wondering if the mistake is something that I did. am I missing some dependeces?

if yes, could you tell me which one?

**Comment by Ejike94** [comment]
The version of Collect that i use is this one:
tightenco/collect                 v6.0.3   Collect - Illuminate Collections as a separate package.

**Comment by mattstauffer** [comment]
@Ejike94 Sorry, the current release of Collect doesn't have LazyCollections in it--but we're fixing that ( #180) and the next dot release will have it.

**Comment by Ejike94** [comment]
Hi,

Thanks for you reply. So after speaking with one of the developers in our company, we notice that there was a line on the code that was not being recognised by php. 

The reason was because apache was running php7.0 whereas, that line of code only works on php7.3

I just had to enable that on the webserver and everything started to work smoothly. 
so i disabled php7.0 for apache and enabled 7.3 using aenmod and dismod
Sorry for this it was my fault, I was running an outdated php
If somebody else has the same problem, that's the fix.

**Comment by mattstauffer** [comment]
I was wrong! It definitely *does* have LazyCollections, and you're right, it was because you were trying to run this package, which requires PHP 7.1, on PHP 7.0. Thanks!
