### ISSUE TITLE
Automate split?

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/collect#2]

**Comment by josephzidell** [comment]
+1

**Comment by JohnathonKoster** [comment]
Is there still interested in automating the split process?

**Comment by mattstauffer** [comment]
@JohnathonKoster yep!

**Comment by JohnathonKoster** [comment]
@mattstauffer i have a few ideas that I will try out and update this issue, most likely tomorrow morning!

**Comment by JohnathonKoster** [comment]
I've made some progress, but there is still a lot of work to do. I have not yet automated the process of updating a repo and releasing new versions with the split Collection components.

Here are some things that do work now:

* Getting a list of new Laravel releases and comparing the list of versions already split;
* Performing the actual split process (uses static analysis to find all the classes/traits needed)
* Getting the required helper functions has been automated (again, using static analysis)
* Automatically correcting for code where the code requires instances of `Illuminate\Database\Eloquent\Collection`
* Running tests on all the split Collection components

Works all the way back to Laravel version `v4.0.0-BETA2`

Here are some things that need to be done:

* Tests. I have not written tests yet.
* Clean up the code (a rushed mess, so many head scratching moments with this project)
* Documentation

The current code can be found here https://github.com/JohnathonKoster/collector (its a mess - you've been warned)

![collector](https://cloud.githubusercontent.com/assets/5232890/18099319/85f1afd6-6eab-11e6-8bed-ffdd197a9fba.gif)

But, for now, I am going to take a break from code for a few hours.

**Comment by JohnathonKoster** [comment]
@mattstauffer 

I've made quite a bit of progress over the last week on a utility to perform the automation process (https://github.com/JohnathonKoster/collector). I have to write the usage docs still, but here is a repository containing the generated output to get a sense of what it can do:

https://github.com/JohnathonKoster/collector-output-test

It split out **119 releases** and pushed them automatically to GitHub only after the PHPUnit tests passed for each release. It took roughly an hour to clone all 203 versions of the Laravel framework, analyze them and push the updates.

**Comment by mattstauffer** [comment]
@JohnathonKoster Awesome, I can't wait to take a look at it--thanks for all of your hard work!

**Comment by JohnathonKoster** [comment]
@mattstauffer Not a problem! If you experience any issues, please let me know!

**Comment by mattstauffer** [comment]
@JohnathonKoster Just FYI: I still appreciate your really hard work here! I apologize I'm so slow on this, life is a bit insane right now--but I *really* appreciate this!

**Comment by JohnathonKoster** [comment]
@mattstauffer Not a problem; I totally understand!

**Comment by clarkeash** [comment]
I just created https://github.com/clarkeash/str inspired by this package, so ill be taking a look at this updater :)

**Comment by mattstauffer** [comment]
I listed this as an issue on our Hacktoberfest list. A pull request here would necessitate a) testing out the proposed splitter and b) making a pull request to the repo with instructions.
