### ISSUE TITLE
Problems with composer dependency install (Tightenco\Collect\Support\Collection' not found)

### ISSUE THREAD

**Issue by timkelty** [tightenco/collect#202]
I've had a few people post having a problem with the Collection dep here: https://github.com/riasvdv/craft-scout/issues/130

I've had people post their composer.json/lock files and zipped up vendor dir, but haven't had a chance to troubleshoot yet.

Wanted to post here first to see if it rang a bell to anyone.

**Comment by Nahuelvvn** [comment]
Did you check PHP version? It looks broken in 7.3

**Comment by Nahuelvvn** [comment]
Did you check PHP versions? Mine was broken with 7.0 but working in 7.1 and above

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
