### ISSUE TITLE
Error Class 'Tightenco\Collect\Support\Debug\Dumper' not found

### ISSUE THREAD

**Issue by NanakiRus** [tightenco/collect#224]
https://github.com/tightenco/collect/blob/79e6bbf22da0e685c8122030374e5db953750b3b/src/Collect/Support/helpers.php#L113

**Comment by mattstauffer** [comment]
Please provide more information. What version of Collect are you using? This is an old bug that I was under the impression was fixed; the only place I can reproduce it is the `5.5.*` line. Are you using a 5.5.* version of Collect? If so, can you upgrade?

**Comment by bakerkretzmar** [comment]
@NanakiRus feel free to open a new issue if you're still getting this error after updating!
