### ISSUE TITLE
Are there breaking changes between 7.x and 8.x?

### ISSUE THREAD

**Issue by I-Valchev** [tightenco/collect#259]
Hi! In https://github.com/bolt/core/pull/2257 we're looking to allow `^7.25 || ^v8.0.0` to clear the way to supporting PHP8 in `bolt/core`. I don't want to switch to `^8.x` yet because that'd mean dropping support for PHP 7.2.

Therefore, are there any breaking changes in this package between 7.x and 8.x? Thanks!

**Comment by mattstauffer** [comment]
@I-Valchev Sorry for the delay; since we only mirror Laravel's Collections package, the best place to ask is there.
