### ISSUE TITLE
Deprecated Notice on PHP 8.1

### ISSUE THREAD

**Issue by webmastervinay** [tightenco/collect#261]
```
Deprecated: Return type of Tightenco\Collect\Support\LazyCollection::jsonSerialize()
```

This warning message is shown on PHP 8.1.  May be the PHP dependency is not updated.

**Comment by assoft** [comment]
This line of code can solve your problem 

`composer global update && valet restart`

**Comment by wturrell** [comment]
@assoft I've already tried this unfortunately, and I already have what I believe are the latest versions: tightenco/collect  v8.34.0 and Laravel 2.16.1.

**Comment by assoft** [comment]
Yes I can confirm that this warning persists. 

However, this does not seem to interfere with the work! You can continue like this for a while (until the update comes) or consider reverting to php 8.0.x.

**Comment by driesvints** [comment]
I'm working on a PR here: https://github.com/tighten/collect/pull/262. Need a maintainer to approve the GHA so I can fix any failing builds.

**Comment by mattstauffer** [comment]
Closed by mistake, Dries still working on it.

**Comment by mattstauffer** [comment]
We fixed this this problem (thanks @jakebathman and @jamisonvalenta!) and updating your `Collect` dependency to `8.68.0` or higher will fix it. If you're running into this issue with Valet, simply run `composer global update`.
