### ISSUE TITLE
PHP 8.1 deprecation warning

### ISSUE THREAD

**Issue by olischmidt123** [tightenco/collect#270]
Just updated to php 8.1 and noticed some deprecation warnings:

Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1449

PHP Deprecated:  Return type of Tightenco\Collect\Support\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1434

Deprecated: Return type of Tightenco\Collect\Support\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1366

**Comment by jamisonvalenta** [comment]
Hello @olischmidt123!  As stated in the documentation, this package is exact copy Illuminate Collection in Laravel/Framework. If you'd like to become more involved, please direct your issues or PRs to `laravel/framework`.  Thanks!
