### ISSUE TITLE
php version issue

### ISSUE THREAD

**Issue by jupitern** [tightenco/collect#273]
Hi,
Requiring symfony/var-dumper v6 limits the compatibility to php8 and in composer.json you have ^7.3|^8.0
This is causing compatibility issues in other packages that require tighten/collect in the chain of dependencies :)

**Comment by jamisonvalenta** [comment]
Hello @jupitern!

Our composer.json requires the following:
```json
    "require": {
        "php": "^7.3|^8.0",
        "symfony/var-dumper": "^3.4 || ^4.0 || ^5.0 || ^6.0"
    },
```
I just double checked this by running a composer install locally under `php@7.3`, and composer successfully installed `symfony/var-dumper@5.4`.  

Perhaps some other package in your project is requiring `symfony/var-dumper@6.*` or requiring `php@8.0`?

**Comment by jupitern** [comment]
Yap. My mistake. thanks.
