### ISSUE TITLE
Fails with dd/dump() 😞

### ISSUE THREAD

**Issue by aaemnnosttv** [tightenco/collect#64]
Using the `dd` or `dump` methods produces a fatal error, regardless of whether `symfony/var-dumper` is installed or not.

`dd` method produces:
```
Fatal error: Uncaught Error: Call to undefined function Illuminate\Support\dd()
```

`dump` method produces:
```
Fatal error: Uncaught Error: Class 'Illuminate\Support\Debug\Dumper' not found
```

Seems to be another dependency from `Illuminate\Support` which is missing.

I'm not sure if this is intentional but I would expect that it should still work.

Using `v5.5.16`

**Comment by mattstauffer** [comment]
Closed by https://github.com/tightenco/collect/pull/65
