### ISSUE TITLE
Same packages installed as on illuminate/support

### ISSUE THREAD

**Issue by augmenter** [tightenco/collect#67]
It seems that the same packages are installed when doing require tightenco/collect or illuminate/support:
symfony:
composer
doctrine
illuminate
nesbot
psr
symfony

tesco:
composer
doctrine
illuminate
nesbot
psr symfony

Am I missing something here?

**Comment by mattstauffer** [comment]
@augmenter If you create a new application and require only `tightenco\collect`, I think you'll find a different list than you have here.
