### ISSUE TITLE
Collect Map/transform arguments as procs

### ISSUE THREAD

**Issue by michaelachrisco** [tightenco/collect#9]
array_map supports a string argument that will call on another function:
```php
$arr = ['first' => 'taylor', 'last' => 'otwell'];
array_map('strtoupper', $arr)
=> [
     "first" => "TAYLOR",
     "last" => "OTWELL",
   ]

?>
```

This is a convenience method as we don't need to push an entire proc to the array_map.
Not sure about the best method to apply, but I believe something like:
```php
      $data = new Collection(['first' => 'taylor', 'last' => 'otwell']);
      $data = $data->mapProc('strtoupper');
```
could be feasible.

**Comment by michaelachrisco** [comment]
Also, not sure if this is the correct place for this feature request or https://github.com/laravel/internals/issues?

**Comment by assertchris** [comment]
@michaelachrisco I think the best place with out in that internals repo first. This repo is intentionally as close to the official API as possible.

**Comment by michaelachrisco** [comment]
Thanks, Ill close this then and re-post over there.
